@echo off
cd /d "%~dp0.."

set NODE_ENV=development
set PORT=3000
set DATABASE_URL=postgresql://postgres:postgres@localhost:55432/ledger_credit_system?schema=public
set JWT_SECRET=local-run-secret-123456
set SUPPORTED_CURRENCIES=USD
set BUSINESS_TIMEZONE=UTC
set CLOSE_WINDOW_CRON=0 0 * * *
set BATCH_SHARD_SIZE=500
set BATCH_WORKER_CONCURRENCY=25
set SCORE_APPROVE_THRESHOLD=700
set SCORE_REJECT_THRESHOLD=550
set RATE_LIMIT_MAX=500
set RATE_LIMIT_WINDOW_MS=60000
set EXTERNAL_RAIL_DEFAULT_PROVIDER=simulator
set EXTERNAL_RAIL_CALLBACK_SECRET=callback-secret
set EXTERNAL_SIMULATOR_SETTLEMENT_DELAY_MS=10
set INTEREST_RATE_BPS=250
set AUTH_ACCESS_TTL_SECONDS=900
set AUTH_REFRESH_TTL_SECONDS=604800
set AUTH_INTERNAL_ISSUER=ledger-credit-system
set AUTH_CUSTOMER_AUDIENCE=customer-api
set AUTH_OPERATOR_AUDIENCE=ops-api

node dist\src\main.js
